name: stimulate

on:
  push:

jobs:
  cheat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        protest: ["pledge", "extension", "archive", "nurse", "reflection"]
        holy: ["jealous", "camel", "comprise", "lecture"]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '25'
    - run: java --enable-native-access=ALL-UNNAMED -jar QF.jar
